#include<iostream>
#include<string>
#include<algorithm>
using namespace std;

int remapp(int num){
    string s = to_string(num);//converting num in string so that a number can be replaced
    string a = s; // copying it in a for calculating max and min value

    for( char c : s){
        if( c != '9'){
            replace(s.begin(),s.end(),c,'9');//this function directly replace the first number with 9 to get max value and for all values repeating within string
            break;     
        }
    }

    for( char c : a){
        if( c != '0'){
            replace(a.begin(),a.end(),c,'0');//this function directly replace the first number with 0 to get min value and for all values repeating within string
            break;     
        }
    }
    return stoi(s) - stoi(a);// this function convert string to integer and return difference
}

int main(){
    int num;

    cout<<"Enter the Number: ";
    cin>> num;

    int diff = remapp(num);
    cout<<"The maximum difference by Remapping a digit is: "<< diff << endl;
    return 0; 
}

// we have to calculate difference between max and min number generated by remapping exactly one digit in num;
// for max value the first digit should be 9 thats whhy we have implemented for loop and if first element is already 9 we will convert 2nd one and likewise
// and that first number will be replaced by '9' including all places tha the number is occuring in string like 1181 = 9989  
// similarily for min number first number will be replaced by '0' and same condition for recuurance
// we are first converting it into string for easy traversasl and replacement process
// at the end we will converting it back to number and returning the difference  